1. Write a Numpy program to get the Numpy version and show the Numpy build configuration.
Click me to see the sample solution

2. Write a NumPy program to get help with the add function.
Click me to see the sample solution

3. Write a NumPy program to test whether none of the elements of a given array are zero. 
Click me to see the sample solution

4. Write a NumPy program to test if any of the elements of a given array are non-zero. 
Click me to see the sample solution

5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).
Click me to see the sample solution

6. Write a NumPy program to test elements-wise for positive or negative infinity. 
Click me to see the sample solution

7. Write a NumPy program to test element-wise for NaN of a given array.
Click me to see the sample solution

8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not. 
Click me to see the sample solution

9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
Click me to see the sample solution

10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
Click me to see the sample solution

11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
Click me to see the sample solution

12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
Click me to see the sample solution

13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 
Click me to see the sample solution

14. Write a NumPy program to create an array of integers from 30 to 70.
Click me to see the sample solution

15.Write a NumPy program to create an array of all even integers from 30 to 70.
Click me to see the sample solution

16. Write a NumPy program to create a 3x3 identity matrix.
Click me to see the sample solution

17. Write a NumPy program to generate a random number between 0 and 1.
Click me to see the sample solution

18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
Click me to see the sample solution

19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
Click me to see the sample solution

20. Write a NumPy program to create a 3X4 array and iterate over it.
Click me to see the sample solution

21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Click me to see the sample solution

22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
Click me to see the sample solution

23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
Click me to see the sample solution

24. Write a NumPy program to multiply the values of two given vectors.
Click me to see the sample solution

25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
Click me to see the sample solution

26. Write a NumPy program to find the number of rows and columns in a given matrix.
Click me to see the sample solution

27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.
Click me to see the sample solution

28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
Click me to see the sample solution

29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
Click me to see the sample solution

30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
Click me to see the sample solution

31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
Click me to see the sample solution

32. Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.
Click me to see the sample solution

33. Write a NumPy program to compute the inner product of two given vectors.
Click me to see the sample solution

34. Write a NumPy program to add a vector to each row of a given matrix.
Click me to see the sample solution

35. Write a NumPy program to save a given array to a binary file .
Click me to see the sample solution

36. Write a NumPy program to save a given array to a binary file.
Click me to see the sample solution

37. Write a NumPy program to save a given array to a text file and load it.
Click me to see the sample solution

38. Write a NumPy program to convert a given array into bytes, and load it as an array.
Click me to see the sample solution

39. Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.
Click me to see the sample solution

40. Write a NumPy program to compute the x and y coordinates for points on a sine curve and plot the points using matplotlib.
Click me to see the sample solution

41. Write a NumPy program to convert numpy dtypes to native Python types
Click me to see the sample solution

42. Write a NumPy program to add elements to a matrix. If an element in the matrix is 0, we will not add the element below this element.
Click me to see the sample solution

43. Write a NumPy program to find missing data in a given array.
Click me to see the sample solution

44. Write a NumPy program to check whether two arrays are equal (element wise) or not.
Click me to see the sample solution

45. Write a NumPy program to create a one-dimensional array of single, two and three-digit numbers.
Click me to see the sample solution

46. Write a NumPy program to create a two-dimensional array of a specified format.
Click me to see the sample solution

47. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1. 
Click me to see the sample solution

48. Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).
Click me to see the sample solution

49. Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.
Click me to see the sample solution

50. Write a NumPy program to create a 4x4 array with random values. Create an array from the said array swapping first and last rows.
Click me to see the sample solution

51. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.
Click me to see the sample solution

52. Write a NumPy program to sort a given array by row and column in ascending order.
Click me to see the sample solution

53. Write a NumPy program to extract all numbers from a given array less and greater than a specified number.
Click me to see the sample solution

54. Write a NumPy program to replace all numbers in a given array equal, less and greater than a given number.
Click me to see the sample solution

55. Write a NumPy program to create an array of equal shape and data type for a given array.
Click me to see the sample solution

56. Write a NumPy program to create a three-dimensional array with the shape (3,5,4) and set it to a variable.
Click me to see the sample solution

57. Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.
Click me to see the sample solution

58. Write a NumPy program to swap rows and columns of a given array in reverse order.
Click me to see the sample solution

59. Write a NumPy program to multiply two given arrays of the same size element-by-element.
Click me to see the sample solution

In [2]:
#1
import numpy as np
print(np.__version__)

2.0.0


In [3]:
#2.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [15]:
#3.
x=np.array([1,0,3,4])
print(np.all(x,0))

False


In [14]:
#4.
x=np.array([1,1,3,4])
print(np.all(x,0))

True


In [17]:
#5. 
y=np.array([1,2,np.inf])
print(np.isfinite(y))

[ True  True False]


In [19]:
#6.
arr=np.array([1,-2,-np.inf,np.inf])
res= np.isposinf(arr)
resw=np.isneginf(arr)
print(res, resw)

[False False False  True] [False False  True False]


In [55]:
#7.
arr=np.array([1,-2,3,np.nan])
res=np.isnan(arr)
res

array([False, False, False,  True])

In [56]:
#8.
arr=np.array([1,-2.j,3.2,np.nan])
rel=np.isreal(arr)
com=np.iscomplex(arr)
sca=np.isscalar(3.1)
print(rel, com, sca)

[ True False  True  True] [False  True False False] True


In [57]:
#9. Dont understand
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)) 


False
True
False
False
True


In [58]:
#10.
x=np.array([1,3,2])
y=np.array([3,1,2])
print(np.greater(x,y))
print(np.less(x,y))
print(np.greater_equal(x,y))
print(np.less_equal(x,y))

[False  True False]
[ True False False]
[False  True  True]
[ True False  True]


In [59]:
#11. Dont understand Tolerance

In [60]:
#12.
X = np.array([1, 7, 13, 105])

print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes


In [61]:
#13.
arr=np.zeros(10,dtype='int8')
print(arr)
arr=np.ones(10,dtype='int8')
print(arr)
arr=np.ones(10,dtype='int8')*5
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


In [62]:
#14.
arr=np.arange(30,71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [63]:
#15.
arr=np.arange(30,71,2)
arr 


array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [64]:
#16
arr=np.identity(3, dtype='int8')
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [65]:
#17.
rando=np.random.randint(0,1,1)
rando

array([0], dtype=int32)

In [12]:
#18.
import numpy as np
arr=np.random.normal(0,1,15)
arr

array([-0.22432612,  1.3881978 , -2.72783465, -0.63652791,  2.16260937,
        1.94649857,  1.8216902 ,  0.87382042,  0.41755516,  1.81970978,
       -1.62408412, -0.64758541, -1.2244392 , -0.13372755,  0.53460814])

In [21]:
#19.
v=np.arange(15,55)
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [24]:
#20.
v=np.arange(0,12).reshape((3,4))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
#21.
o=np.linspace(10,49,5)
o

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

In [42]:
#22 Importante
x=np.arange(21)
x[(x>=9) & (x<=15)]*=-1

print(x)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [44]:
#23
x=np.random.randint(0,15,5)
x

array([10,  7, 14, 11, 13], dtype=int32)

In [45]:
#24
x=np.array([1,2,3])
y=np.array([2,1,3])
print(x*y)

[2 2 9]


In [48]:
#25
x=np.arange(10,22).reshape(3,4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [52]:
#26
x=np.arange(10,22).reshape(3,4)
print(x)
print(x.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


In [53]:
#27
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
#28
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
#29
x=np.diag([1,2,3,4,5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [63]:
#30
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [64]:
#31
x=np.random.random((3, 3, 3))
x

array([[[0.12641931, 0.78842678, 0.2709274 ],
        [0.06153998, 0.10742054, 0.42863524],
        [0.80702323, 0.80919908, 0.1264858 ]],

       [[0.87843989, 0.63957709, 0.9288735 ],
        [0.44903641, 0.25882857, 0.67043872],
        [0.20047602, 0.06544416, 0.80249972]],

       [[0.42043278, 0.41100591, 0.90493212],
        [0.97623177, 0.64846115, 0.64461948],
        [0.86868863, 0.41578074, 0.64485468]]])

In [68]:
#32

x=np.array([[1,2,3],[1,2,3]])
print(x)
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1)) 

[[1 2 3]
 [1 2 3]]
12
[2 4 6]
[6 6]


In [69]:
#33
y=np.array([3,4])
x=np.array([1,2])
print(np.dot(x,y))

11


In [2]:
#34
import numpy as np
# Dont understand
# Creating a NumPy array 'm' representing a matrix with 4 rows and 3 columns
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Creating a NumPy array 'v' representing a vector with 3 elements
v = np.array([1, 1, 0])

# Printing a message indicating the original vector 'v'
print("Original vector:")
print(v)

# Printing a message indicating the original matrix 'm'
print("Original matrix:")
print(m)

# Creating an empty matrix 'result' with the same shape as 'm' using np.empty_like()
result = np.empty_like(m)

# Adding the vector 'v' to each row of the matrix 'm' using a for loop
for i in range(4):
    result[i, :] = m[i, :] + v

# Printing a message indicating the result after adding the vector 'v' to each row of the matrix 'm'
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)

Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


In [3]:
#35
# ?
import os

# Creating a NumPy array 'a' with integers from 0 to 19 using np.arange()
a = np.arange(20)

# Saving the NumPy array 'a' as a file named 'temp_arra.npy' using np.save()
np.save('temp_arra.npy', a)

# Printing a message checking if the file 'temp_arra.npy' exists or not
print("Check if 'temp_arra.npy' exists or not?")

# Checking if the file 'temp_arra.npy' exists using os.path.exists()
if os.path.exists('temp_arra.npy'):
    # Loading the data from 'temp_arra.npy' into 'x2' using np.load()
    x2 = np.load('temp_arra.npy')
    
    # Checking if the loaded array 'x2' is equal to the original array 'a' using np.array_equal()
    print(np.array_equal(a, x2)) 

Check if 'temp_arra.npy' exists or not?
True


In [4]:
#36
# ?
import os

# Creating a NumPy array 'x' containing integers from 0 to 9 using np.arange()
x = np.arange(10)

# Creating a NumPy array 'y' containing integers from 11 to 19 using np.arange()
y = np.arange(11, 20)

# Printing a message indicating the original arrays 'x' and 'y'
print("Original arrays:")
print(x)
print(y)

# Saving the arrays 'x' and 'y' into a '.npz' file named 'temp_arra.npz' using np.savez()
np.savez('temp_arra.npz', x=x, y=y)

# Printing a message indicating loading arrays from the 'temp_arra.npz' file
print("Load arrays from the 'temp_arra.npz' file:")

# Loading data from 'temp_arra.npz' into variables 'x2' and 'y2' using np.load()
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    
    # Printing the loaded arrays 'x2' and 'y2'
    print(x2)
    print(y2) 

Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [5]:
#37
# Importing the NumPy library with an alias 'np'
import numpy as np

# Importing the 'os' module for operating system-dependent functionality
import os

# Creating a NumPy array 'x' with integers from 0 to 11 and reshaping it to a 4x3 matrix using np.arange() and .reshape()
x = np.arange(12).reshape(4, 3)

# Printing a message indicating the original array 'x'
print("Original array:")
print(x)

# Creating a string 'header' containing column names 'col1 col2 col3'
header = 'col1 col2 col3'

# Saving the array 'x' into a text file named 'temp.txt' using np.savetxt()
# Specifying the format as "%d" (integer) and including a header with column names
np.savetxt('temp.txt', x, fmt="%d", header=header)

# Printing a message indicating the content of the text file after loading
print("After loading, content of the text file:")

# Loading the data from 'temp.txt' into the variable 'result' using np.loadtxt()
result = np.loadtxt('temp.txt')

# Printing the loaded data 'result' from the text file
print(result) 

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [6]:
#38
# Importing the NumPy library with an alias 'np'
import numpy as np

# Importing the 'os' module for operating system-dependent functionality
import os

# Creating a NumPy array 'a' containing integers from 1 to 6
a = np.array([1, 2, 3, 4, 5, 6])

# Printing a message indicating the original array 'a'
print("Original array:")
print(a)

# Converting the array 'a' to bytes using a.tobytes() method and storing it in 'a_bytes'
a_bytes = a.tobytes()

# Creating a new NumPy array 'a2' by reading from 'a_bytes' using np.frombuffer()
# Specifying the datatype of 'a2' as the same as 'a' using a.dtype
a2 = np.frombuffer(a_bytes, dtype=a.dtype)

# Printing a message indicating the content of the array after loading from bytes
print("After loading, content of the text file:")
print(a2)

# Checking if both arrays 'a' and 'a2' are equal using np.array_equal()
print(np.array_equal(a, a2)) 

Original array:
[1 2 3 4 5 6]
After loading, content of the text file:
[1 2 3 4 5 6]
True


In [8]:
#39
a=[[1,2],[3,4]]
x=np.array(a)
ad=x.tolist()
print(a==ad)

True


In [88]:
#40
import matplotlib.pyplot as plt

x = np.arange(0, 3 * np.pi, 0.2)
y = np.sin(x)
print("Plot the points using matplotlib:")
plt.plot(x, y)
plt.show() 

In [9]:
#41

x = np.float32(0)
print(type(x))
a = x.item()
print(type(a)) 

<class 'numpy.float32'>
<class 'float'>


In [10]:
#42
def sum_matrix_elements(m):
    arr=np.array(m)
    elements=0

    for p in range(len(arr)):
        for q in range(len(arr[p])):
            if arr[p][q]==0 and p <len(arr)-1:
                arr[p+1][q]=0

            elements+=arr[p][q]
    
    return elements

m = [[1, 1, 0, 2],
     [0, 3, 0, 3],
     [1, 0, 4, 4]]

print(sum_matrix_elements(m))

14


In [4]:
#43
import numpy as np

p=np.array([[1,np.nan,3],[4,5,6],[7,np.nan,9]])
print(np.isnan(p))

[[False  True False]
 [False False False]
 [False  True False]]


In [7]:
#44
y=np.array([[2,2,3],[4,5,7]])
x=np.array([[1,2,3],[4,5,6]])
print(np.equal(x,y))

[[False  True  True]
 [ True  True False]]


In [8]:
#45
single=np.arange(1,10)
double=np.arange(10,100)
triple=np.arange(100,200)
print(single)
print("-"*20)
print(double)
print("-"*20)
print(triple)
print("-"*20)

[1 2 3 4 5 6 7 8 9]
--------------------
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
--------------------
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
--------------------


In [11]:
#46
d=np.arange(1,13).reshape(3,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
#47
np.random.seed(10)

print(np.random.rand(40)) 

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


In [13]:
#48 
# ?

np.random.seed(20) 
cbrt = np.cbrt(7)
nd1 = 200 
print(cbrt * np.random.randn(10, 4) + nd1)   

[[201.6908267  200.37467631 200.68394275 195.51750123]
 [197.92478992 201.07066048 201.79714021 198.1282331 ]
 [200.96238963 200.77744291 200.61875865 199.05613894]
 [198.48492638 198.38860811 197.55239946 200.47003621]
 [199.91545839 202.99877319 202.01069857 200.77735483]
 [199.67739161 193.89831807 202.14273593 202.54951299]
 [199.53450969 199.7512602  199.79145727 202.97687757]
 [200.24634413 196.04606934 198.30611253 197.88701546]
 [201.78450912 203.94032834 198.21152803 196.91446071]
 [201.0082481  197.03285104 200.63052763 197.82590294]]


In [99]:
#49

print(np.random.choice(7, 5))
print(np.random.choice(7, 5, replace=False))
print("\nGenerate a non-uniform random sample with replacement:") 
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))   


In [16]:
#50
nums = np.arange(16, dtype='int').reshape(-1, 4)
print(nums)
nums[[0,-1],:] = nums[[-1,0],:]
print("-"*10)
print(nums) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [19]:
#51
np.zeros((5,6),dtype='int8')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [27]:
#52
num=np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print(num)
print("-"*20)
print (np.sort(num))
print("-"*20)
print(np.sort(num, axis=0))

[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
--------------------
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
--------------------
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [103]:
#53
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])


In [5]:
#54
import numpy as np
num=np.array([1,2,3,5,6,7,8,9])
n=5
print(num[num>n])
print(num[num<n])

[6 7 8 9]
[1 2 3]


In [6]:
#55
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])

print(nums)
print("-"*20)
print(np.zeros_like(nums))

[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]
--------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#56
nums = np.array([[[1, 5, 2, 1],
               [4, 3, 5, 6],
               [6, 3, 0, 6],
               [7, 3, 5, 0],
               [2, 3, 3, 5]],
              
              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],               
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],               
               [2, 0, 2, 8]]]) 

In [12]:
#57
ok= np.arange(16).reshape(-1,4)
new_nums = ok[:, ::-1]
print(ok)
print(new_nums)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [15]:
#58
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print(" "*20)
new_nums = nums[::-1, ::-1]
print(new_nums)

Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]
                    
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


In [20]:
#59
arr1=np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])

arr2=np.array([[6,5,4,3,2,1],[3,2,1,5,6,7]])
print(arr1*arr2)

[[ 6 10 12 12 10  6]
 [ 6  6  4 25 36 49]]


# Linear Algebra

In [58]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print(np.dot(p,q))

[[1 2]
 [3 4]]


In [59]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print(np.outer(p,q))

[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [60]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print(np.cross(p,q))

[ 2 -3]


C:\Users\George Hany\AppData\Local\Temp\ipykernel_36344\1696871098.py:3: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(p,q))


In [62]:
p = [[1, 0], [0, 1]]
print(np.linalg.det(p))

1.0


In [3]:
import numpy as np
#????? 


a = np.array([1,2,3])
b = np.array([0,1,0])

# Display the original 1-D arrays 'a' and 'b'
print("Original 1-d arrays:")
print(a)
print(b)

# Compute the Einstein’s summation convention of the 1-D arrays 'a' and 'b' using np.einsum()
result =  np.einsum("n,n", a, b)
print("Einstein’s summation convention of the said arrays:")
print(result)

# Create two 3x3 arrays 'x' and 'y'
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)

# Display the original higher-dimensional arrays 'x' and 'y'
print("Original Higher dimension:")
print(x)
print(y)

# Compute the Einstein’s summation convention of the 2-D arrays 'x' and 'y' using np.einsum()
result = np.einsum("mk,kn", x, y)
print("Einstein’s summation convention of the said arrays:")
print(result) 

Original 1-d arrays:
[1 2 3]
[0 1 0]
Einstein’s summation convention of the said arrays:
2
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


In [4]:
#??? 

# Create two 1-D arrays 'a' and 'b'
a = np.array([1, 2, 5])
b = np.array([2, 1, 0])

# Display the original 1-D arrays 'a' and 'b'
print("Original 1-d arrays:")
print(a)
print(b)

# Calculate the inner product of arrays 'a' and 'b' using np.inner()
result = np.inner(a, b)

# Display the inner product of the said vectors
print("Inner product of the said vectors:")
print(result)

# Create two 3x3 arrays 'x' and 'y'
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)

# Display the original higher-dimensional arrays 'x' and 'y'
print("Higher dimension arrays:")
print(x)
print(y)

# Calculate the inner product of arrays 'x' and 'y' using np.inner()
result = np.inner(x, y)

# Display the inner product of the said vectors
print("Inner product of the said vectors:")
print(result) 


Original 1-d arrays:
[1 2 5]
[2 1 0]
Inner product of the said vectors:
4
Higher dimension arrays:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Inner product of the said vectors:
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


In [6]:
#???

# Create a matrix 'm' using np.mat() function
m = np.asmatrix("3 -2; 1 0")

# Display the original matrix 'm'
print("Original matrix:")
print("a\n", m)

# Compute the eigenvalues and eigenvectors of the matrix 'm' using np.linalg.eig() function
w, v = np.linalg.eig(m)

# Display the eigenvalues of the said matrix
print("Eigenvalues of the said matrix", w)

# Display the eigenvectors of the said matrix
print("Eigenvectors of the said matrix", v) 


Original matrix:
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:
#???

# Create two 1-dimensional arrays 'a' and 'b'
a = np.array([1, 2, 3])
b = np.array([0, 1, 0])

# Display the original 1-d arrays 'a' and 'b'
print("Original 1-d arrays:")
print(a)
print(b)

# Compute the Kronecker product of the arrays 'a' and 'b' using np.kron() function
result = np.kron(a, b)

# Display the Kronecker product of the said arrays
print("Kronecker product of the said arrays:")
print(result)

# Create two 3x3 arrays 'x' and 'y'
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)

# Display the original higher dimension arrays 'x' and 'y'
print("Original Higher dimension:")
print(x)
print(y)

# Compute the Kronecker product of the arrays 'x' and 'y' using np.kron() function
result = np.kron(x, y)

# Display the Kronecker product of the said arrays
print("Kronecker product of the said arrays:")
print(result) 


Original 1-d arrays:
[1 2 3]
[0 1 0]
Kronecker product of the said arrays:
[0 1 0 0 2 0 0 3 0]
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Kronecker product of the said arrays:
[[ 0  0  0  3  4  5  6  8 10]
 [ 0  0  0  6  7  8 12 14 16]
 [ 0  0  0  9 10 11 18 20 22]
 [ 9 12 15 12 16 20 15 20 25]
 [18 21 24 24 28 32 30 35 40]
 [27 30 33 36 40 44 45 50 55]
 [18 24 30 21 28 35 24 32 40]
 [36 42 48 42 49 56 48 56 64]
 [54 60 66 63 70 77 72 80 88]]


In [9]:
#??? 

# Import 'linalg' module from NumPy and alias it as 'LA'
from numpy import linalg as LA

# Create a 3x3 NumPy array 'a'
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])

# Display the original matrix 'a'
print("Original matrix:")
print(a)

# Calculate and display the condition number of the matrix 'a' using LA.cond() function
print("The condition number of the said matrix:")
print(LA.cond(a))


Original matrix:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


In [10]:

# Create a NumPy array 'v' containing elements from 0 to 6
v = np.arange(7)

# Calculate the L2 norm (Euclidean norm) of the vector 'v'
result = np.linalg.norm(v)

# Display the computed L2 norm of the vector 'v'
print("Vector norm:")
print(result)

# Create a 2x2 matrix 'm' using the np.matrix function
m = np.matrix('1, 2; 3, 4') 

# Calculate the Frobenius norm of the matrix 'm'
result1 = np.linalg.norm(m)

# Display the computed Frobenius norm of the matrix 'm'
print("Matrix norm:")
print(result1)


Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


In [11]:
# Import the NumPy library and alias it as 'np'
import numpy as np

# Create a 2x2 NumPy array 'a' containing specific values
a = np.array([[1,2],[3,4]])

# Display the original array 'a'
print("Original array:")
print(a)

# Calculate the determinant of the array 'a' using np.linalg.det() function
result =  np.linalg.det(a)

# Display the determinant of the array 'a'
print("Determinant of the said array:")
print(result) 


Original array:
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


In [13]:
#>???????

# Create a 2x2 NumPy array 'm' containing specific values
m = np.array([[1,2],[3,4]])

# Display the original matrix 'm'
print("Original matrix:")
print(m)

# Calculate the inverse of the matrix 'm' using np.linalg.inv() function
result =  np.linalg.inv(m)

# Display the inverse of the matrix 'm'
print("Inverse of the said matrix:")
print(result) 


Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
#?????

# Importing the NumPy library
import numpy as np

# Create a 2x2 NumPy array 'm' containing specific values
m = np.array([[1, 2], [3, 4]])

# Display the original matrix 'm'
print("Original matrix:")
print(m)

# Perform QR decomposition on the matrix 'm' using np.linalg.qr() function
result = np.linalg.qr(m)

# Display the QR decomposition of the matrix 'm'
print("Decomposition of the said matrix:")
print(result) 


Original matrix:
[[1 2]
 [3 4]]
Decomposition of the said matrix:
QRResult(Q=array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), R=array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


In [16]:
#???????

# Create a 2x2 NumPy array 'm' containing specific values
m = np.array([[1, 2], [3, 4]])

# Display the original matrix 'm'
print("Original matrix:")
print(m)

# Perform QR decomposition on the matrix 'm' using np.linalg.qr() function
result = np.linalg.qr(m)

# Display the QR decomposition of the matrix 'm'
print("Decomposition of the said matrix:")
print(result) 


Original matrix:
[[1 2]
 [3 4]]
Decomposition of the said matrix:
QRResult(Q=array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), R=array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


# NUMPY RANDOM EXERCISES

In [19]:
x=np.random.normal(size=5)
x

array([-1.32201543, -1.60124489,  0.16277668, -0.17622247,  0.32039291])

In [21]:
x=np.random.randint(10,30,6)
x

array([11, 27, 26, 29, 24, 21], dtype=int32)

In [28]:
x=np.random.random((3,3,3))
x

array([[[0.4139063 , 0.19101721, 0.00656313],
        [0.27994952, 0.93930492, 0.96818096],
        [0.30559222, 0.10417465, 0.12350528]],

       [[0.53126551, 0.56494986, 0.68000117],
        [0.99098975, 0.78985009, 0.94628801],
        [0.50317819, 0.13098475, 0.92151338]],

       [[0.20787913, 0.90867132, 0.06206208],
        [0.85172175, 0.23557876, 0.74686177],
        [0.954131  , 0.88234415, 0.22098692]]])

In [34]:
x=np.random.random((5,5))
print(x)
print(np.min(x))
print(x.min())
print(np.max(x))
print(x.max())


[[0.83560076 0.60005324 0.03328921 0.01253735 0.29601332]
 [0.30042001 0.75720128 0.77879497 0.53120279 0.07281786]
 [0.36365833 0.65573985 0.22053176 0.62374668 0.10365241]
 [0.25429208 0.65355724 0.71999234 0.07450036 0.73757052]
 [0.86823574 0.56891085 0.58475211 0.26548121 0.99163331]]
0.012537351341126435
0.012537351341126435
0.9916333091475815
0.9916333091475815


In [35]:
x = np.random.rand(10, 4)

# Printing the original array 'x'
print("Original array:")
print(x)

# Selecting the first 5 rows of the array 'x' and storing it in variable 'y' using array slicing
y = x[:5, :]

# Printing the first 5 rows of the original array 'x' stored in 'y'
print("First 5 rows of the above array:")
print(y) 

Original array:
[[0.16786231 0.85022531 0.17543617 0.02286662]
 [0.95435782 0.83117318 0.13709268 0.26649195]
 [0.51460746 0.28676052 0.9941193  0.03028179]
 [0.75439969 0.38701327 0.61998265 0.46404087]
 [0.47076577 0.39316631 0.73506314 0.78985092]
 [0.72054972 0.0403443  0.97850024 0.60479531]
 [0.6209225  0.333235   0.13494232 0.24528393]
 [0.24766596 0.86918252 0.7443181  0.56024482]
 [0.50193499 0.76808673 0.82846243 0.70425872]
 [0.07568672 0.45730113 0.69930164 0.68111421]]
First 5 rows of the above array:
[[0.16786231 0.85022531 0.17543617 0.02286662]
 [0.95435782 0.83117318 0.13709268 0.26649195]
 [0.51460746 0.28676052 0.9941193  0.03028179]
 [0.75439969 0.38701327 0.61998265 0.46404087]
 [0.47076577 0.39316631 0.73506314 0.78985092]]


In [36]:


x = np.arange(10)


np.random.shuffle(x)
print(x)


[4 0 8 9 5 2 6 3 1 7]


In [39]:
x = np.random.random((3, 3))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin) / (xmax - xmin)
print(x) 

[[0.4133784  0.24400835 0.27744081]
 [0.99045282 0.57379043 0.06446631]
 [0.19205991 0.31755084 0.53144474]]
[[0.3768004  0.19389271 0.2299974 ]
 [1.         0.55003406 0.        ]
 [0.13779207 0.27331341 0.50430371]]


In [41]:
x = np.random.random(10)
x.sort()
print(x)

[0.0330555  0.14428147 0.27662874 0.28309606 0.33945046 0.42780008
 0.54181412 0.56487659 0.61728679 0.85253544]


In [43]:
#?????
x = np.random.uniform(1, 12, 5)
v = 4

# Finding the value 'n' in 'x' that is closest to 'v'
# Using np.abs(x - v).argmin() to get the index of the element in 'x' closest to 'v'
# Accessing the element using x.flat[index] to get the closest value 'n'
n = x.flat[np.abs(x - v).argmin()]

# Printing the value 'n' that is closest to 'v'
print(n) 


4.499660581903197


In [56]:
x=np.random.randint((1,5))
print(x)
y=np.random.randint((1,5))
print(y)
print(np.equal(x,y))

[0 1]
[0 2]
[ True False]


In [58]:
x=np.random.random(15)
print(x)
x[x.argmax()]=-1
print(x)

[0.47723807 0.7515247  0.85090466 0.00552885 0.52636304 0.64022845
 0.99218985 0.58584546 0.75613284 0.02985105 0.37625827 0.29558159
 0.28242698 0.6057739  0.60747468]
[ 0.47723807  0.7515247   0.85090466  0.00552885  0.52636304  0.64022845
 -1.          0.58584546  0.75613284  0.02985105  0.37625827  0.29558159
  0.28242698  0.6057739   0.60747468]


In [60]:
x = np.random.randint(0, 10, 40)

print("Original array:")
print(x)
most = np.bincount(x).argmax()
print(most)

Original array:
[8 5 9 1 1 0 7 2 5 9 4 9 7 1 3 7 1 1 7 3 5 0 7 3 6 8 8 8 3 2 5 4 4 4 4 6 0
 1 7 5]
1


In [61]:
#?????


# Importing the NumPy library as np
import numpy as np

# Generating a random 10x2 array 'z' with random numbers between 0 and 1
z = np.random.random((10, 2))

# Extracting the first column as 'x' and the second column as 'y' from the array 'z'
x, y = z[:, 0], z[:, 1]

# Calculating the Euclidean distance (r) using the formula sqrt(x^2 + y^2)
r = np.sqrt(x**2 + y**2)

# Calculating the angles (t) using arctan2() function, which returns the arctangent of y/x in radians
t = np.arctan2(y, x)

# Displaying the calculated Euclidean distances (r)
print(r)

# Displaying the calculated angles (t) in radians
print(t)


[1.02645195 1.05502234 1.28868152 1.0193787  0.4858836  0.78010665
 0.38580513 0.61199337 1.30819332 0.33008167]
[0.93529167 1.21079009 0.76926852 0.35951009 0.42080233 1.40463069
 0.79369357 1.48789112 0.8629762  0.51694182]


In [62]:
#????

# Creating an array 'x' containing numbers from 0 to 99 using arange() function
x = np.arange(100)

# Displaying the original array 'x'
print("Original array:")
print(x)

# Generating a random floating-point number 'a' between 0 and 100
a = np.random.uniform(0, 100)

# Displaying the value used for comparison
print("Value to compare:")
print(a)

# Finding the index of the element in array 'x' closest to the generated value 'a'
index = (np.abs(x - a)).argmin()

# Displaying the element in 'x' that is closest to the generated value 'a'
print(x[index]) 


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
92.64042071697841
93


In [63]:

# Creating an array 'x' containing numbers from 0 to 9 using arange() function
x = np.arange(10)

# Displaying the original array 'x'
print("Original array:")
print(x)

# Shuffling the elements in array 'x'
np.random.shuffle(x)

# Selecting the 'n' largest elements in 'x' using argsort and slicing
n = 1
print(x[np.argsort(x)[-n:]]) 


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [64]:
#?????? 
# Importing NumPy library and aliasing it as np
import numpy as np

# Setting the random seed to 32 for reproducibility
np.random.seed(32)

# Generating a 3D NumPy array 'nums' with dimensions 300x400x5
# Filling it with random integers in the range [0, 256) and data type uint8
nums = np.random.randint(low=0, high=256, size=(300, 400, 5), dtype=np.uint8)

# Printing the generated array 'nums'
print(nums) 


[[[215  42 224 219  43]
  [166  69  15 133 255]
  [105  95  54  37 201]
  ...
  [240  22  66 232 132]
  [ 13  85  53 220 170]
  [249  62 221 146  69]]

 [[ 73  79 148 132 164]
  [  3  93  98 138 200]
  [174  34  31 208 130]
  ...
  [ 15 252  41  64  39]
  [188 216 223 124  27]
  [ 85 112 240 116 231]]

 [[227  50 243  20 171]
  [ 12  66 108 102  63]
  [107  54   0   0 173]
  ...
  [215  46  57  99 151]
  [243 199  31  28 179]
  [143   7  30 175 190]]

 ...

 [[214  64  64 212  62]
  [140  44 217  17 164]
  [226 146 247  53 199]
  ...
  [189  68  49 117  63]
  [ 14  17 109  82  92]
  [155 221 135 184 231]]

 [[132 194 160 136 102]
  [132 244 230 117 181]
  [146 245  21 164  29]
  ...
  [125 240 243 190 240]
  [137  41 157 117 155]
  [ 20  92  72 182  41]]

 [[120  45 198 218 190]
  [ 42 150 190 103 106]
  [164  71 220 114  59]
  ...
  [143  20 219 154  85]
  [219 190 170 227 246]
  [ 39  14 127 230 158]]]


# Numpy Array Exercise

In [54]:
import numpy as np
print(np.__version__)

2.0.0


In [55]:
li=[1,2,3,4]
nm=np.array(li)
print(li)
print(" "*20)
print(nm)

[1, 2, 3, 4]
                    
[1 2 3 4]


In [7]:
num=np.arange(2,11).reshape(3,3)
num

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [10]:
num=np.zeros(10)
num[6]=11
num

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [14]:
num=np.arange(12,38)
num

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [16]:
arr=np.array([1,2,3,4,5])
num=arr[::-1]
num

array([5, 4, 3, 2, 1])

In [21]:
arr=np.array([1,2,3,4,5])
x = np.asarray(arr,dtype='float')
x

array([1., 2., 3., 4., 5.])

In [26]:
arr=np.ones([5,5])
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
#???
x= np.ones((3, 3))

# Printing the original array 'x'
print("Original array:")
print(x)

# Modifying the array 'x' to set 0s on the border and 1s inside the array using the np.pad function
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)

# Printing the modified array 'x' with 0s on the border and 1s inside
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:

x = np.ones((3, 3))
print("Checkerboard pattern:")
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1  
x[::2, 1::2] = 1 
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
li=[1,2,3,4,5,6,7,8]
print(np.asarray(li))
to=([1,2,3,4],[5,6,7,8])
print(np.asarray(to))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [38]:
arr=np.array([10,20,30])
arr=np.append(arr,[40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [42]:
x=np.empty((3,4))
print(x)
print(' '*20)
y=np.full((3,4),6)
print(y)


[[1.34588477e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [2.67018234e-306 2.42260564e-052 6.87624756e+169 1.69021379e-052]
 [2.90212193e+180 1.04035764e-042 2.10938177e-052 1.72047406e+184]]
                    
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [43]:
# List of Fahrenheit values
fvalues = [0, 12, 45.21, 34, 99.91, 32]

# Creating a NumPy array from the Fahrenheit values list
F = np.array(fvalues)

# Printing the Fahrenheit values
print("Values in Fahrenheit degrees:")
print(F)

# Converting Fahrenheit values to Centigrade degrees and printing the result
print("Values in  Centigrade degrees:")
print(np.round((5 * F / 9 - 5 * 32 / 9), 2))

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91 32.  ]
Values in  Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [44]:
# ????

x = np.sqrt([1 + 0j])

# Calculating square root of another complex number
y = np.sqrt([0 + 1j])

# Printing the original array 'x' and 'y'
print("Original array:x ", x)
print("Original array:y ", y)

# Printing the real part of the array 'x' and 'y'
print("Real part of the array:")
print(x.real)
print(y.real)

# Printing the imaginary part of the array 'x' and 'y'
print("Imaginary part of the array:")
print(x.imag)
print(y.imag) 

Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


In [45]:
x = np.array([1, 2, 3])
print(x.size)
print(x.itemsize)
print(x.nbytes)

3
8
24


In [47]:
x1=np.array([0,1,2,3,4])
x2=np.array([0,1,7,4,5])
print(np.isin(x1,x2))

[ True  True False False  True]


In [48]:
x1=np.array([0,1,2,3,4])
x2=np.array([0,1,7,4,5])
print(np.intersect1d(x1,x2))

[0 1 4]


In [49]:
x=np.array([1,1,2,3,3,4,5,5,6])
print(np.unique(x))

[1 2 3 4 5 6]


In [50]:
x1=np.array([0,1,2,3,4])
x2=np.array([0,1,7,4,5])
print(np.setdiff1d(x1,x2))

[2 3]


In [51]:
x1=np.array([0,1,2,3,4])
x2=np.array([0,1,7,4,5])
print(np.setxor1d(x1,x2)) 

[2 3 5 7]


In [53]:
print(np.all([[True,False],[True,True]]))  
print(np.all([[True,True],[True,True]]))  

print(np.all([10, 20, 0, -50]))   
print(np.all([10, 20, -50])) 

False
True
False
True


# Stopped at 24