1. Write a Numpy program to get the Numpy version and show the Numpy build configuration.
Click me to see the sample solution

2. Write a NumPy program to get help with the add function.
Click me to see the sample solution

3. Write a NumPy program to test whether none of the elements of a given array are zero. 
Click me to see the sample solution

4. Write a NumPy program to test if any of the elements of a given array are non-zero. 
Click me to see the sample solution

5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).
Click me to see the sample solution

6. Write a NumPy program to test elements-wise for positive or negative infinity. 
Click me to see the sample solution

7. Write a NumPy program to test element-wise for NaN of a given array.
Click me to see the sample solution

8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not. 
Click me to see the sample solution

9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
Click me to see the sample solution

10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
Click me to see the sample solution

11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
Click me to see the sample solution

12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
Click me to see the sample solution

13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 
Click me to see the sample solution

14. Write a NumPy program to create an array of integers from 30 to 70.
Click me to see the sample solution

15.Write a NumPy program to create an array of all even integers from 30 to 70.
Click me to see the sample solution

16. Write a NumPy program to create a 3x3 identity matrix.
Click me to see the sample solution

17. Write a NumPy program to generate a random number between 0 and 1.
Click me to see the sample solution

18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
Click me to see the sample solution

19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
Click me to see the sample solution

20. Write a NumPy program to create a 3X4 array and iterate over it.
Click me to see the sample solution

21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Click me to see the sample solution

22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
Click me to see the sample solution

23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
Click me to see the sample solution

24. Write a NumPy program to multiply the values of two given vectors.
Click me to see the sample solution

25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
Click me to see the sample solution

26. Write a NumPy program to find the number of rows and columns in a given matrix.
Click me to see the sample solution

27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.
Click me to see the sample solution

28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
Click me to see the sample solution

29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
Click me to see the sample solution

30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
Click me to see the sample solution

31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
Click me to see the sample solution

32. Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.
Click me to see the sample solution

33. Write a NumPy program to compute the inner product of two given vectors.
Click me to see the sample solution

34. Write a NumPy program to add a vector to each row of a given matrix.
Click me to see the sample solution

35. Write a NumPy program to save a given array to a binary file .
Click me to see the sample solution

36. Write a NumPy program to save a given array to a binary file.
Click me to see the sample solution

37. Write a NumPy program to save a given array to a text file and load it.
Click me to see the sample solution

38. Write a NumPy program to convert a given array into bytes, and load it as an array.
Click me to see the sample solution

39. Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.
Click me to see the sample solution

40. Write a NumPy program to compute the x and y coordinates for points on a sine curve and plot the points using matplotlib.
Click me to see the sample solution

41. Write a NumPy program to convert numpy dtypes to native Python types
Click me to see the sample solution

42. Write a NumPy program to add elements to a matrix. If an element in the matrix is 0, we will not add the element below this element.
Click me to see the sample solution

43. Write a NumPy program to find missing data in a given array.
Click me to see the sample solution

44. Write a NumPy program to check whether two arrays are equal (element wise) or not.
Click me to see the sample solution

45. Write a NumPy program to create a one-dimensional array of single, two and three-digit numbers.
Click me to see the sample solution

46. Write a NumPy program to create a two-dimensional array of a specified format.
Click me to see the sample solution

47. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1. 
Click me to see the sample solution

48. Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).
Click me to see the sample solution

49. Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.
Click me to see the sample solution

50. Write a NumPy program to create a 4x4 array with random values. Create an array from the said array swapping first and last rows.
Click me to see the sample solution

51. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.
Click me to see the sample solution

52. Write a NumPy program to sort a given array by row and column in ascending order.
Click me to see the sample solution

53. Write a NumPy program to extract all numbers from a given array less and greater than a specified number.
Click me to see the sample solution

54. Write a NumPy program to replace all numbers in a given array equal, less and greater than a given number.
Click me to see the sample solution

55. Write a NumPy program to create an array of equal shape and data type for a given array.
Click me to see the sample solution

56. Write a NumPy program to create a three-dimensional array with the shape (3,5,4) and set it to a variable.
Click me to see the sample solution

57. Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.
Click me to see the sample solution

58. Write a NumPy program to swap rows and columns of a given array in reverse order.
Click me to see the sample solution

59. Write a NumPy program to multiply two given arrays of the same size element-by-element.
Click me to see the sample solution

In [2]:
#1
import numpy as np
print(np.__version__)

2.0.0


In [3]:
#2.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [15]:
#3.
x=np.array([1,0,3,4])
print(np.all(x,0))

False


In [14]:
#4.
x=np.array([1,1,3,4])
print(np.all(x,0))

True


In [17]:
#5. 
y=np.array([1,2,np.inf])
print(np.isfinite(y))

[ True  True False]


In [19]:
#6.
arr=np.array([1,-2,-np.inf,np.inf])
res= np.isposinf(arr)
resw=np.isneginf(arr)
print(res, resw)

[False False False  True] [False False  True False]


In [55]:
#7.
arr=np.array([1,-2,3,np.nan])
res=np.isnan(arr)
res

array([False, False, False,  True])

In [56]:
#8.
arr=np.array([1,-2.j,3.2,np.nan])
rel=np.isreal(arr)
com=np.iscomplex(arr)
sca=np.isscalar(3.1)
print(rel, com, sca)

[ True False  True  True] [False  True False False] True


In [57]:
#9. Dont understand
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)) 


False
True
False
False
True


In [58]:
#10.
x=np.array([1,3,2])
y=np.array([3,1,2])
print(np.greater(x,y))
print(np.less(x,y))
print(np.greater_equal(x,y))
print(np.less_equal(x,y))

[False  True False]
[ True False False]
[False  True  True]
[ True False  True]


In [59]:
#11. Dont understand Tolerance

In [60]:
#12.
X = np.array([1, 7, 13, 105])

print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes


In [61]:
#13.
arr=np.zeros(10,dtype='int8')
print(arr)
arr=np.ones(10,dtype='int8')
print(arr)
arr=np.ones(10,dtype='int8')*5
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


In [62]:
#14.
arr=np.arange(30,71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [63]:
#15.
arr=np.arange(30,71,2)
arr 


array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [64]:
#16
arr=np.identity(3, dtype='int8')
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [65]:
#17.
rando=np.random.randint(0,1,1)
rando

array([0], dtype=int32)

In [12]:
#18.
import numpy as np
arr=np.random.normal(0,1,15)
arr

array([-0.22432612,  1.3881978 , -2.72783465, -0.63652791,  2.16260937,
        1.94649857,  1.8216902 ,  0.87382042,  0.41755516,  1.81970978,
       -1.62408412, -0.64758541, -1.2244392 , -0.13372755,  0.53460814])

In [21]:
#19.
v=np.arange(15,55)
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [24]:
#20.
v=np.arange(0,12).reshape((3,4))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
#21.
o=np.linspace(10,49,5)
o

array([10.  , 19.75, 29.5 , 39.25, 49.  ])

In [42]:
#22 Importante
x=np.arange(21)
x[(x>=9) & (x<=15)]*=-1

print(x)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [44]:
#23
x=np.random.randint(0,15,5)
x

array([10,  7, 14, 11, 13], dtype=int32)

In [45]:
#24
x=np.array([1,2,3])
y=np.array([2,1,3])
print(x*y)

[2 2 9]


In [48]:
#25
x=np.arange(10,22).reshape(3,4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [52]:
#26
x=np.arange(10,22).reshape(3,4)
print(x)
print(x.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


In [53]:
#27
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
#28
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
#29
x=np.diag([1,2,3,4,5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [63]:
#30
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [64]:
#31
x=np.random.random((3, 3, 3))
x

array([[[0.12641931, 0.78842678, 0.2709274 ],
        [0.06153998, 0.10742054, 0.42863524],
        [0.80702323, 0.80919908, 0.1264858 ]],

       [[0.87843989, 0.63957709, 0.9288735 ],
        [0.44903641, 0.25882857, 0.67043872],
        [0.20047602, 0.06544416, 0.80249972]],

       [[0.42043278, 0.41100591, 0.90493212],
        [0.97623177, 0.64846115, 0.64461948],
        [0.86868863, 0.41578074, 0.64485468]]])

In [68]:
#32

x=np.array([[1,2,3],[1,2,3]])
print(x)
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1)) 

[[1 2 3]
 [1 2 3]]
12
[2 4 6]
[6 6]


In [69]:
#33
y=np.array([3,4])
x=np.array([1,2])
print(np.dot(x,y))

11


In [2]:
#34
import numpy as np
# Dont understand
# Creating a NumPy array 'm' representing a matrix with 4 rows and 3 columns
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Creating a NumPy array 'v' representing a vector with 3 elements
v = np.array([1, 1, 0])

# Printing a message indicating the original vector 'v'
print("Original vector:")
print(v)

# Printing a message indicating the original matrix 'm'
print("Original matrix:")
print(m)

# Creating an empty matrix 'result' with the same shape as 'm' using np.empty_like()
result = np.empty_like(m)

# Adding the vector 'v' to each row of the matrix 'm' using a for loop
for i in range(4):
    result[i, :] = m[i, :] + v

# Printing a message indicating the result after adding the vector 'v' to each row of the matrix 'm'
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)

Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


In [3]:
#35
# ?
import os

# Creating a NumPy array 'a' with integers from 0 to 19 using np.arange()
a = np.arange(20)

# Saving the NumPy array 'a' as a file named 'temp_arra.npy' using np.save()
np.save('temp_arra.npy', a)

# Printing a message checking if the file 'temp_arra.npy' exists or not
print("Check if 'temp_arra.npy' exists or not?")

# Checking if the file 'temp_arra.npy' exists using os.path.exists()
if os.path.exists('temp_arra.npy'):
    # Loading the data from 'temp_arra.npy' into 'x2' using np.load()
    x2 = np.load('temp_arra.npy')
    
    # Checking if the loaded array 'x2' is equal to the original array 'a' using np.array_equal()
    print(np.array_equal(a, x2)) 

Check if 'temp_arra.npy' exists or not?
True


In [4]:
#36
# ?
import os

# Creating a NumPy array 'x' containing integers from 0 to 9 using np.arange()
x = np.arange(10)

# Creating a NumPy array 'y' containing integers from 11 to 19 using np.arange()
y = np.arange(11, 20)

# Printing a message indicating the original arrays 'x' and 'y'
print("Original arrays:")
print(x)
print(y)

# Saving the arrays 'x' and 'y' into a '.npz' file named 'temp_arra.npz' using np.savez()
np.savez('temp_arra.npz', x=x, y=y)

# Printing a message indicating loading arrays from the 'temp_arra.npz' file
print("Load arrays from the 'temp_arra.npz' file:")

# Loading data from 'temp_arra.npz' into variables 'x2' and 'y2' using np.load()
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    
    # Printing the loaded arrays 'x2' and 'y2'
    print(x2)
    print(y2) 

Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [5]:
#37
# Importing the NumPy library with an alias 'np'
import numpy as np

# Importing the 'os' module for operating system-dependent functionality
import os

# Creating a NumPy array 'x' with integers from 0 to 11 and reshaping it to a 4x3 matrix using np.arange() and .reshape()
x = np.arange(12).reshape(4, 3)

# Printing a message indicating the original array 'x'
print("Original array:")
print(x)

# Creating a string 'header' containing column names 'col1 col2 col3'
header = 'col1 col2 col3'

# Saving the array 'x' into a text file named 'temp.txt' using np.savetxt()
# Specifying the format as "%d" (integer) and including a header with column names
np.savetxt('temp.txt', x, fmt="%d", header=header)

# Printing a message indicating the content of the text file after loading
print("After loading, content of the text file:")

# Loading the data from 'temp.txt' into the variable 'result' using np.loadtxt()
result = np.loadtxt('temp.txt')

# Printing the loaded data 'result' from the text file
print(result) 

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [6]:
#38
# Importing the NumPy library with an alias 'np'
import numpy as np

# Importing the 'os' module for operating system-dependent functionality
import os

# Creating a NumPy array 'a' containing integers from 1 to 6
a = np.array([1, 2, 3, 4, 5, 6])

# Printing a message indicating the original array 'a'
print("Original array:")
print(a)

# Converting the array 'a' to bytes using a.tobytes() method and storing it in 'a_bytes'
a_bytes = a.tobytes()

# Creating a new NumPy array 'a2' by reading from 'a_bytes' using np.frombuffer()
# Specifying the datatype of 'a2' as the same as 'a' using a.dtype
a2 = np.frombuffer(a_bytes, dtype=a.dtype)

# Printing a message indicating the content of the array after loading from bytes
print("After loading, content of the text file:")
print(a2)

# Checking if both arrays 'a' and 'a2' are equal using np.array_equal()
print(np.array_equal(a, a2)) 

Original array:
[1 2 3 4 5 6]
After loading, content of the text file:
[1 2 3 4 5 6]
True


In [8]:
#39
a=[[1,2],[3,4]]
x=np.array(a)
ad=x.tolist()
print(a==ad)

True


In [88]:
#40
import matplotlib.pyplot as plt

x = np.arange(0, 3 * np.pi, 0.2)
y = np.sin(x)
print("Plot the points using matplotlib:")
plt.plot(x, y)
plt.show() 

In [9]:
#41

x = np.float32(0)
print(type(x))
a = x.item()
print(type(a)) 

<class 'numpy.float32'>
<class 'float'>


In [10]:
#42
def sum_matrix_elements(m):
    arr=np.array(m)
    elements=0

    for p in range(len(arr)):
        for q in range(len(arr[p])):
            if arr[p][q]==0 and p <len(arr)-1:
                arr[p+1][q]=0

            elements+=arr[p][q]
    
    return elements

m = [[1, 1, 0, 2],
     [0, 3, 0, 3],
     [1, 0, 4, 4]]

print(sum_matrix_elements(m))

14


In [4]:
#43
import numpy as np

p=np.array([[1,np.nan,3],[4,5,6],[7,np.nan,9]])
print(np.isnan(p))

[[False  True False]
 [False False False]
 [False  True False]]


In [7]:
#44
y=np.array([[2,2,3],[4,5,7]])
x=np.array([[1,2,3],[4,5,6]])
print(np.equal(x,y))

[[False  True  True]
 [ True  True False]]


In [8]:
#45
single=np.arange(1,10)
double=np.arange(10,100)
triple=np.arange(100,200)
print(single)
print("-"*20)
print(double)
print("-"*20)
print(triple)
print("-"*20)

[1 2 3 4 5 6 7 8 9]
--------------------
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
--------------------
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]
--------------------


In [11]:
#46
d=np.arange(1,13).reshape(3,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
#47
np.random.seed(10)

print(np.random.rand(40)) 

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


In [13]:
#48 
# ?

np.random.seed(20) 
cbrt = np.cbrt(7)
nd1 = 200 
print(cbrt * np.random.randn(10, 4) + nd1)   

[[201.6908267  200.37467631 200.68394275 195.51750123]
 [197.92478992 201.07066048 201.79714021 198.1282331 ]
 [200.96238963 200.77744291 200.61875865 199.05613894]
 [198.48492638 198.38860811 197.55239946 200.47003621]
 [199.91545839 202.99877319 202.01069857 200.77735483]
 [199.67739161 193.89831807 202.14273593 202.54951299]
 [199.53450969 199.7512602  199.79145727 202.97687757]
 [200.24634413 196.04606934 198.30611253 197.88701546]
 [201.78450912 203.94032834 198.21152803 196.91446071]
 [201.0082481  197.03285104 200.63052763 197.82590294]]


In [99]:
#49

print(np.random.choice(7, 5))
print(np.random.choice(7, 5, replace=False))
print("\nGenerate a non-uniform random sample with replacement:") 
print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))   


In [16]:
#50
nums = np.arange(16, dtype='int').reshape(-1, 4)
print(nums)
nums[[0,-1],:] = nums[[-1,0],:]
print("-"*10)
print(nums) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [19]:
#51
np.zeros((5,6),dtype='int8')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [27]:
#52
num=np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print(num)
print("-"*20)
print (np.sort(num))
print("-"*20)
print(np.sort(num, axis=0))

[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
--------------------
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
--------------------
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [103]:
#53
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])


In [5]:
#54
import numpy as np
num=np.array([1,2,3,5,6,7,8,9])
n=5
print(num[num>n])
print(num[num<n])

[6 7 8 9]
[1 2 3]


In [6]:
#55
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])

print(nums)
print("-"*20)
print(np.zeros_like(nums))

[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]
--------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#56
nums = np.array([[[1, 5, 2, 1],
               [4, 3, 5, 6],
               [6, 3, 0, 6],
               [7, 3, 5, 0],
               [2, 3, 3, 5]],
              
              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],               
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],               
               [2, 0, 2, 8]]]) 

In [12]:
#57
ok= np.arange(16).reshape(-1,4)
new_nums = ok[:, ::-1]
print(ok)
print(new_nums)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [15]:
#58
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print(" "*20)
new_nums = nums[::-1, ::-1]
print(new_nums)

Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]
                    
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


In [20]:
#59
arr1=np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])

arr2=np.array([[6,5,4,3,2,1],[3,2,1,5,6,7]])
print(arr1*arr2)

[[ 6 10 12 12 10  6]
 [ 6  6  4 25 36 49]]
